### PR TITLE
Remove ticket actions by ID

### PR DESCRIPTION
**Pull request by jarrydlee**

### CODE REVIEW

**Comment by kalebdavis** [comment]
The code changes are :+1: but can you tell me what the reason for this change is?

**Comment by jarrydlee** [comment]
It doesn't make sense to remove actions from a ticket by some of the fields in it when there is a uuid that I can use.

**Comment by kalebdavis** [comment]
So you'll always know the ID or be able to get it?

**Comment by jarrydlee** [comment]
Yeah, well have it or be able to get it

**Comment by kalebdavis** [comment]
:shipit:

**Pull request merged**
